spring:
  application:
    name: deepexi-com
  profiles:
    active: local
  dubbo:
    application:
      name: deepexi-com
    protocol:
      name: dubbo
      port: 20880
    consumer:
      check: false
    registry:
      check: false
swagger:
  base-package: com.deepexi.controller
  info:
    title: deepexi-com
server:
  port: 8080
logging:
  file: 'logs/${spring.application.name}.log'
management:
  server:
    port: 15600
